In [1]:
import numpy as  np
arr=np.array([2,3,4,5,6,7,8,9,10])
new_arr=[]
for i in arr:
    new_arr.append(i+10)
print(new_arr)


[12, 13, 14, 15, 16, 17, 18, 19, 20]


In [2]:
arr1=np.array([2,3,4,5,6,7,8,9,10])
new_arr=arr1**2
new_arr

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [3]:
arr2=arr1+20
arr2

array([22, 23, 24, 25, 26, 27, 28, 29, 30])

Broadcasting with Arrays of Different Shapes

In [4]:
b_arr=np.array([[1,2,3,4],[5,6,7,8]])
c_arr=np.array([10,20,30,40])
n_arr=b_arr+c_arr
n_arr

array([[11, 22, 33, 44],
       [15, 26, 37, 48]])

Hands-on: Applying Broadcasting to Real-World Scenarios

In [5]:
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])

mean=data.mean(axis=0)
std=data.std(axis=0)
normalized=(data-mean)/std
print(normalized)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
