In [1]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [4]:
np.full((4,6),9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [8]:
#checking array properties

In [9]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [10]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
myarr.shape


(4, 3)

In [12]:
myarr.size

12

In [13]:
myarr.ndim

2

In [14]:
myarr.dtype

dtype('int32')

In [15]:
#changing datatype in numpy

In [16]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]] ,dtype="float32")
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [17]:
arr_int=myarr.astype(np.int32)
arr_int.dtype



dtype('int32')

In [18]:
myarr.dtype

dtype('float32')

In [19]:
#reshaping


In [20]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [21]:
myarr.shape

(4, 3)

In [22]:
reshaped=myarr.reshape((3,4)) #change to shape like which is the multiplew of 12 ex:2,6 _ 4,3 etc

In [23]:
reshaped



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
myarr.flatten() # convert to 1d array direct

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])