In [3]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1.shape)

(3, 3)


In [4]:
even_num=arr1%2==0
print(arr1[even_num])

[2 4 6 8]


In [5]:
arr_num=np.array([1,2,3,4,5,6,7,8,9])
print(arr_num.reshape((3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr_new_num=np.array([78, 45, 92 ,61 ,37, 88 ,54 ,73, 29 ,96, 81, 67, 43, 59 ,25, 84, 33, 70 ,90 ,49])
fil=arr_new_num>70
print(arr_new_num[fil])

[78 92 88 73 96 81 84 90]


In [11]:
a=np.array([1,2,3,4,5,6,7,8],dtype=np.float32)
print(a.dtype)
int_a=a.astype(np.int32)
print(int_a.dtype)

float32
int32
