In [1]:
#indexing and slicing

In [3]:
import numpy as np
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
flat=myarr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[0]

1

In [10]:
flat[3:6] # n-1

array([4, 5, 6])

In [12]:
flat[:5] # same as o to 5

array([1, 2, 3, 4, 5])

In [13]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
flat[::3] # o th  to the gap of _:_:3 

array([ 1,  4,  7, 10])

so the most important numpy not make copy suppose 
i have flat and i print in a variable from 2 index to 5 index
so the variable have the array 2 to 5 as n
no if i change that variable array by varuiable[0]= 444444 value , it will reflect to the main flat array 

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
a=flat[2:6]
print(a)

[3 4 5 6]


In [19]:
a[0]=5050505

In [20]:
a

array([5050505,       4,       5,       6])

In [21]:
#but twist is this that it chnages to flat also not only in a variable 

In [22]:
flat

array([      1,       2, 5050505,       4,       5,       6,       7,
             8,       9,      10,      11,      12])

so slicing retrun a view not a copy! changes affect the original array

WHY IT USED?
FOR FAST AND EFFICIENT
IF COPY IT MIGHT SLOW


In [24]:
#IF I HAVE TO MAKE A COPY .copy() method
A=flat[2:11].copy()
A

array([5050505,       4,       5,       6,       7,       8,       9,
            10,      11])

In [27]:
A[0]=398355
A


array([398355,      4,      5,      6,      7,      8,      9,     10,
           11])

In [28]:
flat

array([      1,       2, 5050505,       4,       5,       6,       7,
             8,       9,      10,      11,      12])

In [29]:
#so it not affect the original

In [34]:
#fancy indexing
array1=np.array([1,234,5,46,5675,77])
array1[[0,2,5]]#how to use fancy indexing


array([ 1,  5, 77])

In [35]:
#boolean masking filter data

In [38]:
array2=np.array([1,2,5,46,55,7])
array2[array2>5]

array([46, 55,  7])

In [40]:
#ONE MORE EXAMPLE
array3=np.array([1,2,5,4,5,7])
con=array3>2
array3[con]

array([5, 4, 5, 7])