In [1]:
#speed test

In [2]:
import numpy as np
import time
#python list
size=1_000_000_0
list1=list(range(size))
list2=list(range(size))
start=time.time()
result=[x + y for x, y in zip(list1,list2)]
end=time.time()
print(end-start)


0.6482589244842529


In [3]:
#Numpy array
size=1_000_000_0
list1=np.array(list(range(size)))
list2=np.array(list(range(size)))
start=time.time()
result=list1+list2
end=time.time()
print(end-start)

0.11703014373779297


In [4]:
#zip example how to zip the two list in python not in numpy
list1=[1,2,3,4]
list2=[6,7,8,9]
list(zip(list1,list2))

[(1, 6), (2, 7), (3, 8), (4, 9)]

In [5]:
#creating 1d and 2d array

In [6]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr2=np.array([[1,2,3,4,5],[4,5,6,9,2]])
arr2

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 9, 2]])

In [9]:
print(f"the type of 1d amd 2d array{type(arr2)} and the shape of both as 1D {arr1.shape} and 2D {arr2.shape}")

the type of 1d amd 2d array<class 'numpy.ndarray'> and the shape of both as 1D (10,) and 2D (2, 5)


In [10]:
#memory optimization in numpy

In [11]:
import sys
list_data=list(range(100))
numpy_data=np.array(list_data)
print(f"the size of list data in python is {sys.getsizeof(list_data)*len(list_data) } bytes")
print(f"the size of array in numpy compareed to list is {numpy_data.nbytes}")

the size of list data in python is 85600 bytes
the size of array in numpy compareed to list is 400


In [12]:
#no more loops in python now we see how to do it
list=[1,2,3,4,5,6,7,8,9,10]
ans=[x**2 for x in list]
ans

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [13]:
numpy_arr=np.array([1,2,3,4,5,6,7,8,9,10])
res=numpy_arr**2
res

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])