In [2]:
# 📘 Student Marks Analyzer using NumPy


import numpy as np

# Sample marks data: 5 students, 4 subjects
marks = np.array([
    [78, 82, 91, 75],  # Student 1
    [88, 74, 67, 92],  # Student 2
    [90, 87, 85, 88],  # Student 3
    [65, 70, 60, 72],  # Student 4
    [95, 89, 94, 90]   # Student 5
])

print("📊 Marks of Students (Rows = Students, Columns = Subjects):\n")
print(marks)

# 1️⃣ Average marks of each student
student_avg = np.mean(marks, axis=1)
print("\n🎯 Average marks of each student:")
for i, avg in enumerate(student_avg, start=1):
    print(f"Student {i}: {avg:.2f}")

# 2️⃣ Average marks in each subject
subject_avg = np.mean(marks, axis=0)
subject_names = ['Math', 'Physics', 'Chemistry', 'English']
print("\n📘 Average marks per subject:")
for name, avg in zip(subject_names, subject_avg):
    print(f"{name}: {avg:.2f}")

# 3️⃣ Standard deviation of each student
print("\n📐 Standard deviation of each student:")
std_dev = np.std(marks, axis=1)
for i, std in enumerate(std_dev, start=1):
    print(f"Student {i}: {std:.2f}")

# 4️⃣ Highest and lowest marks per subject
print("\n🏆 Highest marks in each subject:")
for name, score in zip(subject_names, np.max(marks, axis=0)):
    print(f"{name}: {score}")

print("\n⬇️ Lowest marks in each subject:")
for name, score in zip(subject_names, np.min(marks, axis=0)):
    print(f"{name}: {score}")

# 5️⃣ Top scoring student
total_marks = np.sum(marks, axis=1)
top_student = np.argmax(total_marks) + 1
print(f"\n🥇 Top Scorer: Student {top_student} with {total_marks[top_student - 1]} total marks.")

# 6️⃣ Each student's best subject
print("\n📌 Each student's best subject:")
for i, row in enumerate(marks):
    best_subject = np.argmax(row)
    print(f"Student {i + 1}: {subject_names[best_subject]} ({row[best_subject]} marks)")


📊 Marks of Students (Rows = Students, Columns = Subjects):

[[78 82 91 75]
 [88 74 67 92]
 [90 87 85 88]
 [65 70 60 72]
 [95 89 94 90]]

🎯 Average marks of each student:
Student 1: 81.50
Student 2: 80.25
Student 3: 87.50
Student 4: 66.75
Student 5: 92.00

📘 Average marks per subject:
Math: 83.20
Physics: 80.40
Chemistry: 79.40
English: 83.40

📐 Standard deviation of each student:
Student 1: 6.02
Student 2: 10.16
Student 3: 1.80
Student 4: 4.66
Student 5: 2.55

🏆 Highest marks in each subject:
Math: 95
Physics: 89
Chemistry: 94
English: 92

⬇️ Lowest marks in each subject:
Math: 65
Physics: 70
Chemistry: 60
English: 72

🥇 Top Scorer: Student 5 with 368 total marks.

📌 Each student's best subject:
Student 1: Chemistry (91 marks)
Student 2: English (92 marks)
Student 3: Math (90 marks)
Student 4: English (72 marks)
Student 5: Math (95 marks)
