In [1]:
import numpy as np
arr2=np.array([[1,2,3,4,],
               [5,6,7,8]])
arr3=np.array([[[2,3,4,5],
                [6,7,8,9]],  
               
               [[1,7,5,3],
                [2,8,2,1]]])
arr1=np.array([1,2,3,4,5,6,7,8,9])
# so there are three types of dimensin in array 1d ,2d ,3d
print(sum(arr1))


45


In [2]:
print(np.sum(arr2,axis=0))
print(np.sum(arr2,axis=1)) #in this we said 0 axis means from 0th row and add 1st element + 1th rows 1st element and then 2nd row and so on

[ 6  8 10 12]
[10 26]


#indexing 2d array in multidimensional arrays

In [3]:
print(arr2[1,2]) #answer is 7 exp- we said that go to 1st row and then its 2 index number

7


In [4]:
print(arr2[0,3]) #ans-4

4


In [5]:
print(arr2[0:2,1:4]) #ans= 2,6,3,7,4,8

[[2 3 4]
 [6 7 8]]


In [6]:
print(arr2[:2, :3]) # 1,2,3 and5,6,7

[[1 2 3]
 [5 6 7]]


In [7]:
arr3.shape #it contains 0,1 depth , {0,1 row }, {0,1,2,3 colomns} why because indexing refers to n-1

(2, 2, 4)

In [8]:
arr3[1,1,2] # correct is 2

2

In [9]:
arr3[0,1,3]

9

In [10]:
print(arr3[:, 0, :]) #[[2,3,4,5] and    [[1,7,5,3],

[[2 3 4 5]
 [1 7 5 3]]


In [11]:
arr2[:, 0] # 1,5


array([1, 5])

In [12]:
arr3[:, 0, :] #[[2,3,4,5] , [1, 7, 5, 3]

array([[2, 3, 4, 5],
       [1, 7, 5, 3]])

In [13]:
arr2[:,2]=0

In [14]:
arr2

array([[1, 2, 0, 4],
       [5, 6, 0, 8]])

In [15]:
arr3[:,1,1]

array([7, 8])

In [16]:
arr3[:,1,1]=0


In [17]:
arr3

array([[[2, 3, 4, 5],
        [6, 0, 8, 9]],

       [[1, 7, 5, 3],
        [2, 0, 2, 1]]])